### PR TITLE
Fix broken json output on some systems

### LINKED ISSUE #193: Invalid JSON output on specific platforms like AWS CodeBuild
### Current Behavior

Typical usage:
  `$ helm secrets terraform secrets/myproject/nginx/secrets.yaml`

Would output: 
```json
{"content_base64":"<base64 coded content
 of value file>"}
```
(notice unexpected new line)

This is no longer a valid json.
This happens because `base64` on some platforms wraps output by default
ref: https://superuser.com/questions/1225134/why-does-the-base64-of-a-string-contain-n

This when used in terraform, the terraform produces this error:

`invalid character '\n' in string literal'; 'Unexpected External Program Results on data.tf line 2, in data "external" "helm-secrets"`

### Expected Behavior

should produce a valid JSON output on all platforms
like:
```json
{"content_base64":"<base64 coded content of value file>"}
```

### Steps To Reproduce

```markdown
run the Typical usage command: 
`helm secrets terraform secrets/myproject/nginx/secrets.yaml`
```

### Environment

- Helm Version: v3.8.0
- Helm Secrets Version: 3.12.0
- OS: aws/codebuild/standard:5.0
- Shell: sh

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by kanaksinghal**
**What this PR does / why we need it**:

Fix broken json output on some systems

Running my TF on AWS CodeBuild image: `aws/codebuild/standard:5.0`

Typical usage:
  `$ helm secrets terraform secrets/myproject/nginx/secrets.yaml`

Would output: 
```json
{"content_base64":"<base64 coded content
 of value file>"}
```
(notice unexpected new line)

This is no longer a valid json.
This happens because `base64` on some platforms wraps output by default
ref: https://superuser.com/questions/1225134/why-does-the-base64-of-a-string-contain-n

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #193

**Special notes for your reviewer**:

**PR Readiness Checklist**:

Complete these before marking the PR as `ready to review`:

- [x] the `CHANGELOG.md` release notes have been updated to reflect any significant (and particularly user-facing) changes introduced by this PR

### CODE REVIEW

File: scripts/commands/terraform.sh [hunk 1]
```diff
@@ -30,5 +30,5 @@ terraform() {
         exit 1
     fi
 
-    printf '{"content_base64":"%s"}' "$(printf '%s' "${content}" | base64)"
+    printf '{"content_base64":"%s"}' "$(printf '%s' "${content}" | base64 | tr -d \\n)"
```
Comment (jkroepke) [inline scripts/commands/terraform.sh:33]: I would prefer to use `base64 -w0` instead of an additional pipe/subprocess.

But there is no `-w` parameter on MacOS (but `-w0` is default). I guess its fine for now.

**Comment by jkroepke** [comment]
Can you add a test that ensure only 1 line is printed?

https://github.com/jkroepke/helm-secrets/blob/main/tests/unit/terraform.bats

File: scripts/commands/terraform.sh (hunk 1 above)
Comment (kanaksinghal) [reply scripts/commands/terraform.sh:33]: Right. I was about to use -w but ran a last minute check on local and got invalid flag error.

**Comment by jkroepke** [comment]
Thanks for the contribution!

**Review by jkroepke — APPROVED** [review]
